name: Keycloak Guides

on:
  push:
    branches-ignore:
      - main
      - dependabot/**
      - quarkus-next
  pull_request:
  workflow_dispatch:

env:
  MAVEN_ARGS: "-B -nsu -Daether.connector.http.connectionMaxTtl=25"

concurrency:
  # Only cancel jobs for PR updates
  group: guides-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  conditional:
    name: Check conditional workflows and jobs
    runs-on: ubuntu-22.04
    outputs:
      guides: ${{ steps.conditional.outputs.guides }}
      ci: ${{ steps.conditional.outputs.ci }}
    permissions: write-all
    timeout-minutes: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde6

      - id: conditional
        name: Check conditions
        uses: ./.github/actions/conditional
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    # will only build the guides if the general CI doesn't run, which will also build the guides
    if: ${{ needs.conditional.outputs.guides == 'true' && needs.conditional.outputs.ci != 'true' }}
    runs-on: ubuntu-22.04
    needs: conditional
    permissions: write-all
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde6

      - name: Build Keycloak
        uses: ./.github/actions/build-keycloak

  check:
    name: Status Check - Keycloak Guides
    if: always()
    needs:
      - conditional
      - build
    runs-on: ubuntu-22.04
    permissions: write-all
    timeout-minutes: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde6
      - name: Do status check
        uses: ./.github/actions/status-check
        with:
          jobs: ${{ toJSON(needs) }}
