name: Keycloak JavaScript CI

on:
  push:
    branches-ignore:
      - main
      - dependabot/**
      - quarkus-next
  pull_request:
  workflow_dispatch:

env:
  MAVEN_ARGS: "-B -nsu -Daether.connector.http.connectionMaxTtl=25"

concurrency:
  # Only cancel jobs for PR updates
  group: js-ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  conditional:
    name: Check conditional workflows and jobs
    runs-on: ubuntu-22.04
    permissions: {}
    outputs:
      js-ci: ${{ steps.conditional.outputs.js }}
    timeout-minutes: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde6

      - id: conditional
        name: Run conditional checks
        uses: ./.github/actions/conditional
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build-keycloak:
    name: Build Keycloak
    needs: conditional
    if: needs.conditional.outputs.js-ci == 'true'
    runs-on: ubuntu-22.04
    permissions: write-all
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde6

      - name: Setup Java
        uses: actions/setup-java@99b8673
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
          cache: maven

      - name: Build Keycloak
        run: ./mvnw clean install --errors -DskipTests -DskipTestsuite -DskipExamples -Pdistribution
      - name: Move build
        run: mv ./quarkus/dist/target/keycloak-999.0.0-SNAPSHOT.tar.gz ./keycloak-999.0.0-SNAPSHOT.tar.gz

      - name: Upload Keycloak dist
        uses: actions/upload-artifact@a8a3f3a
        if: github.repository == 'keycloak/keycloak'
        with:
          name: keycloak
          path: keycloak-999.0.0-SNAPSHOT.tar.gz

  admin-client:
    name: Admin Client
    needs: conditional
    if: needs.conditional.outputs.js-ci == 'true'
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    permissions: {}
    env:
      WORKSPACE: "@keycloak/keycloak-admin-client"
    steps:
      - name: Checkout repository
        uses: actions/checkout@a8a3f3a

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup
        with:
          working-directory: js

      - name: Run linter
        run: pnpm --filter ${{ env.WORKSPACE }} run lint
        working-directory: js

      - name: Run build
        run: pnpm --filter ${{ env.WORKSPACE }} run build
        working-directory: js

  keycloak-js:
    name: Keycloak JS
    needs: conditional
    if: needs.conditional.outputs.js-ci == 'true'
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    permissions: {}
    env:
      WORKSPACE: keycloak-js
    steps:
      - name: Checkout repository
        uses: actions/checkout@a8a3f3a

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup
        with:
          working-directory: js

      - name: Run build
        run: pnpm --filter ${{ env.WORKSPACE }} run build
        working-directory: js

  keycloak-masthead:
    name: Keycloak Masthead
    needs: conditional
    if: needs.conditional.outputs.js-ci == 'true'
    runs-on: ubuntu-22.04
    env:
      WORKSPACE: keycloak-masthead
    permissions: {}
    timeout-minutes: 3
    steps:
      - name: Checkout repository
        uses: actions/checkout@a8a3f3a

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup
        with:
          working-directory: js

      - name: Run linter
        run: pnpm --filter ${{ env.WORKSPACE }} run lint
        working-directory: js

      - name: Run build
        run: pnpm --filter ${{ env.WORKSPACE }} run build
        working-directory: js

  ui-shared:
    name: UI Shared
    needs: conditional
    if: needs.conditional.outputs.js-ci == 'true'
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    env:
      WORKSPACE: ui-shared
    permissions: {}
    steps:
      - name: Checkout repository
        uses: actions/checkout@a8a3f3a

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup
        with:
          working-directory: js

      - name: Run linter
        run: pnpm --filter ${{ env.WORKSPACE }} run lint
        working-directory: js

      - name: Run build
        run: pnpm --filter ${{ env.WORKSPACE }} run build
        working-directory: js

  account-ui:
    name: Account UI
    needs: conditional
    if: needs.conditional.outputs.js-ci == 'true'
    runs-on: ubuntu-22.04
    env:
      WORKSPACE: account-ui
    permissions: {}
    timeout-minutes: 3
    steps:
      - name: Checkout repository
        uses: actions/checkout@a8a3f3a

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup
        with:
          working-directory: js

      - name: Run linter
        run: pnpm --filter ${{ env.WORKSPACE }} run lint
        working-directory: js

      - name: Run build
        run: pnpm --filter ${{ env.WORKSPACE }} run build
        working-directory: js

  admin-ui:
    name: Admin UI
    needs: conditional
    if: needs.conditional.outputs.js-ci == 'true'
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    permissions: {}
    env:
      WORKSPACE: admin-ui
    steps:
      - name: Do checkout
        uses: actions/checkout@a8a3f3a

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup
        with:
          working-directory: js

      - name: Run linter
        run: pnpm --filter ${{ env.WORKSPACE }} run lint
        working-directory: js

      - name: Run tests
        run: pnpm --filter ${{ env.WORKSPACE }} run test
        working-directory: js

      - name: Run build
        run: pnpm --filter ${{ env.WORKSPACE }} run build
        working-directory: js

      - name: Run typechecker
        run: pnpm --filter ${{ env.WORKSPACE }} run cy:check-types
        working-directory: js

  account-ui-e2e:
    name: Account UI E2E
    timeout-minutes: 20
    needs:
      - conditional
      - build-keycloak
    if: needs.conditional.outputs.js-ci == 'true'
    runs-on: ubuntu-22.04
    env:
      WORKSPACE: account-ui
    permissions: write-all
    steps:
      - name: Checkour repository
        uses: actions/checkout@a8a3f3a

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup
        with:
          working-directory: js

      - name: Download Keycloak server
        uses: actions/download-artifact@9bc31d5
        with:
          name: keycloak

      - name: Setup Java
        uses: actions/setup-java@99b8673
        with:
          distribution: temurin
          java-version: 17

      - name: Unpak keycloak
        run: tar xfvz keycloak-999.0.0-SNAPSHOT.tar.gz

      - name: Start Keycloak server
        run: keycloak-999.0.0-SNAPSHOT/bin/kc.sh start-dev --features=transient-users &> ~/server.log &
        env:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin

      - name: Install Playwright browsers
        run: pnpm --filter ${{ env.WORKSPACE }} exec playwright@1.42.1 install --with-deps
        working-directory: js

      - name: Run Playwright tests
        run: pnpm --filter ${{ env.WORKSPACE }} run test
        working-directory: js
        env:
          KEYCLOAK_SERVER: http://localhost:8080

      - name: Upload playwright report
        uses: actions/upload-artifact@a8a3f3a
        if: ${{ always() &&  github.repository == 'keycloak/keycloak' }}
        with:
          name: account-ui-playwright-report
          path: js/apps/${{ env.WORKSPACE }}/playwright-report
          retention-days: 30

      - name: Upload server logs
        if: ${{ always() &&  github.repository == 'keycloak/keycloak' }}
        uses: actions/upload-artifact@a8a3f3a
        with:
          name: account-ui-server-log
          path: ~/server.log


  admin-ui-e2e:
    name: Admin UI E2E
    needs:
      - conditional
      - build-keycloak
    if: needs.conditional.outputs.js-ci == 'true' && github.repository == 'keycloak/keycloak'
    runs-on: ubuntu-22.04
    env:
      WORKSPACE: admin-ui
    strategy:
      matrix:
        container: [1, 2, 3, 4, 5]
        browser: [chrome, firefox]
        exclude:
          # Only test with Firefox on scheduled runs
          - browser: ${{ github.event_name != 'workflow_dispatch' && 'firefox' || '' }}
    permissions: write-all
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@a8a3f3a

      - name: Install Google Chrome
        if: matrix.browser == 'chrome'
        uses: browser-actions/setup-chrome@97349de
        with:
          chrome-version: stable

      - name: Install Firefox
        if: matrix.browser == 'firefox'
        uses: browser-actions/setup-firefox@233224b
        with:
          firefox-version: latest

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup
        with:
          working-directory: js

      - name: Compile Admin Client
        run: pnpm --filter @keycloak/keycloak-admin-client run build
        working-directory: js

      - name: Download Keycloak server
        uses: actions/download-artifact@9bc31d5
        with:
          name: keycloak

      - name: Setup Java
        uses: actions/setup-java@99b8673
        with:
          distribution: temurin
          java-version: 17

      - name: Unpack keycloak
        run: tar xfvz keycloak-999.0.0-SNAPSHOT.tar.gz

      - name: Start Keycloak server
        run: keycloak-999.0.0-SNAPSHOT/bin/kc.sh start-dev --features=admin-fine-grained-authz,transient-users &> ~/server.log &
        env:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin

      - name: Start LDAP server
        run: pnpm --filter ${{ env.WORKSPACE }} run cy:ldap-server &
        working-directory: js

      - name: Run Cypress
        uses: cypress-io/github-action@1b70233
        with:
          install: false
          browser: ${{ matrix.browser }}
          wait-on: http://localhost:8080
          working-directory: js/apps/admin-ui
        env:
          CYPRESS_BASE_URL: http://localhost:8080/admin/
          CYPRESS_KEYCLOAK_SERVER: http://localhost:8080
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}

      - name: Upload server logs
        if: ${{ always() && github.repository == 'keycloak/keycloak'}}
        uses: actions/upload-artifact@a8a3f3a
        with:
          name: admin-ui-server-log-${{ matrix.container }}-${{ matrix.browser }}
          path: ~/server.log

      - name: Upload Cypress videos
        uses: actions/upload-artifact@a8a3f3a
        if: always() && github.repository != 'keycloak/keycloak-private'
        with:
          name: cypress-videos-${{ matrix.container }}-${{ matrix.browser }}
          path: js/apps/admin-ui/cypress/videos
          if-no-files-found: ignore
          retention-days: 10

  check:
    name: Status Check - Keycloak JavaScript CI
    timeout-minutes: 1
    if: always()
    permissions: {}
    needs:
      - conditional
      - build-keycloak
      - admin-client
      - keycloak-js
      - keycloak-masthead
      - ui-shared
      - account-ui
      - account-ui-e2e
      - admin-ui
      - admin-ui-e2e
    runs-on: ubuntu-22.10
    steps:
      - name: Checkout repository
        uses: actions/checkout@a8a3f3a
      - name: Check workflow status
        uses: ./.github/actions/status-check
        with:
          jobs: ${{ toJSON(needs) }}
