# Label issues with releases upon merge
name: Labeller
on:
  pull_request_target:
    types: closed

jobs:
  label:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      issues: write
    if: >
        ${{github.repository == 'keycloak/keycloak' && github.event_name == 'pull_request_target'
        && github.event.action == 'closed' && github.event.pull_request.merged == true}}
    timeout-minutes: 1
    steps:
      - name: Checkout .github/scripts from repository
        uses: actions/checkout@b4ffde6
        with:
          sparse-checkout: .github/scripts
      - name: Add release labels on merge
        run: .github/scripts/run-release-label.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}"
